Repository opensearch-project/search-relevance, pull requests merged in 2025-06, with the labels that each got.

#31 Adding experiment variant entity
  CHANGELOG.md
  src/main/java/org/opensearch/searchrelevance/common/PluginConstants.java
  src/main/java/org/opensearch/searchrelevance/dao/ExperimentVariantDao.java
  src/main/java/org/opensearch/searchrelevance/experiment/ExperimentOptionsForHybridSearch.java
  src/main/java/org/opensearch/searchrelevance/experiment/ExperimentVariantHybridSearchDTO.java
  src/main/java/org/opensearch/searchrelevance/experiment/QuerySourceUtil.java
  src/main/java/org/opensearch/searchrelevance/indices/SearchRelevanceIndices.java
  src/main/java/org/opensearch/searchrelevance/metrics/MetricsHelper.java
  src/main/java/org/opensearch/searchrelevance/model/ExperimentType.java
  src/main/java/org/opensearch/searchrelevance/model/ExperimentVariant.java
  src/main/java/org/opensearch/searchrelevance/plugin/SearchRelevancePlugin.java
  src/main/java/org/opensearch/searchrelevance/transport/experiment/PutExperimentTransportAction.java
  src/main/resources/mappings/experiment_variant.json
  src/test/java/org/opensearch/searchrelevance/experiment/QuerySourceUtilTests.java
  src/test/java/org/opensearch/searchrelevance/plugin/SearchRelevancePluginTests.java
Labels: enhancement

#40 Added validation for hybrid query structure
  CHANGELOG.md
  src/main/java/org/opensearch/searchrelevance/experiment/QuerySourceUtil.java
  src/main/java/org/opensearch/searchrelevance/model/builder/SearchRequestBuilder.java
  src/test/java/org/opensearch/searchrelevance/experiment/QuerySourceUtilTests.java
  src/test/java/org/opensearch/searchrelevance/model/builder/SearchRequestBuilderTests.java
Labels: enhancement

#43 Flipping default feature flag setting to disabled
  build.gradle
  src/main/java/org/opensearch/searchrelevance/settings/SearchRelevanceSettings.java
  src/test/java/org/opensearch/searchrelevance/plugin/SearchRelevancePluginTests.java
Labels: skip-changelog, do-not-merge

#51 Enabled dynamic mapping mode for complex types in index mapping
  src/main/resources/mappings/evaluation_result.json
  src/main/resources/mappings/experiment.json
  src/main/resources/mappings/experiment_variant.json
  src/main/resources/mappings/judgment.json
Labels: bug, skip-changelog

#59 Adding CI action to run integ tests with security enabled
  .github/workflows/test_security.yml
Labels: skip-changelog, infrastructure

#65 Added lazy index creation for APIs
  CHANGELOG.md
  src/main/java/org/opensearch/searchrelevance/indices/SearchRelevanceIndices.java
  src/main/java/org/opensearch/searchrelevance/indices/SearchRelevanceIndicesManager.java
  src/main/java/org/opensearch/searchrelevance/transport/experiment/DeleteExperimentTransportAction.java
  src/main/java/org/opensearch/searchrelevance/transport/experiment/GetExperimentTransportAction.java
  src/main/java/org/opensearch/searchrelevance/transport/judgment/DeleteJudgmentTransportAction.java
  src/main/java/org/opensearch/searchrelevance/transport/judgment/GetJudgmentTransportAction.java
  src/main/java/org/opensearch/searchrelevance/transport/queryset/DeleteQuerySetTransportAction.java
  src/main/java/org/opensearch/searchrelevance/transport/queryset/GetQuerySetTransportAction.java
  src/main/java/org/opensearch/searchrelevance/transport/searchConfiguration/DeleteSearchConfigurationTransportAction.java
  src/main/java/org/opensearch/searchrelevance/transport/searchConfiguration/GetSearchConfigurationTransportAction.java
  src/test/java/org/opensearch/searchrelevance/indices/SearchRelevanceIndicesTests.java
Labels: bug, v3.1.0

#64 Migrate from judgment score to judgment rating for the name
  CHANGELOG.md
  src/main/java/org/opensearch/searchrelevance/judgments/BaseJudgmentsProcessor.java
  src/main/java/org/opensearch/searchrelevance/judgments/ImportJudgmentsProcessor.java
  src/main/java/org/opensearch/searchrelevance/judgments/LlmJudgmentsProcessor.java
  src/main/java/org/opensearch/searchrelevance/judgments/UbiJudgmentsProcessor.java
  src/main/java/org/opensearch/searchrelevance/judgments/clickmodel/coec/CoecClickModel.java
  src/main/java/org/opensearch/searchrelevance/metrics/EvaluationMetrics.java
  src/main/java/org/opensearch/searchrelevance/metrics/MetricsHelper.java
  src/main/java/org/opensearch/searchrelevance/metrics/calculator/Evaluation.java
  src/main/java/org/opensearch/searchrelevance/model/Judgment.java
  src/main/java/org/opensearch/searchrelevance/model/JudgmentCache.java
  src/main/java/org/opensearch/searchrelevance/rest/RestPutJudgmentAction.java
  src/main/java/org/opensearch/searchrelevance/transport/judgment/PutImportJudgmentRequest.java
  src/main/java/org/opensearch/searchrelevance/transport/judgment/PutJudgmentTransportAction.java
  src/main/resources/mappings/judgment.json
  src/main/resources/mappings/judgment_cache.json
  src/test/java/org/opensearch/searchrelevance/action/judgment/PutJudgmentActionTests.java
  src/test/java/org/opensearch/searchrelevance/rest/RestPutJudgmentActionTests.java
  src/test/scripts/create_judgments_with_manual_input.sh
  src/test/scripts/demo.sh
Labels: v3.1.0

#68 Added basic integ tests for QuerySet and SearchConfig APIs
  src/test/java/org/opensearch/searchrelevance/BaseSearchRelevanceIT.java
  src/test/java/org/opensearch/searchrelevance/action/queryset/QuerySetIT.java
  src/test/java/org/opensearch/searchrelevance/action/searchConfiguration/SearchConfigurationIT.java
  src/test/resources/queryset/CreateQuerySet.json
  src/test/resources/searchconfig/CreateSearchConfiguration.json
Labels: skip-changelog, infrastructure, v3.1.0

#61 Use the size parameter to do the calculations
  src/main/java/org/opensearch/searchrelevance/metrics/EvaluationMetrics.java
  src/main/java/org/opensearch/searchrelevance/metrics/MetricsHelper.java
  src/main/java/org/opensearch/searchrelevance/metrics/calculator/Evaluation.java
  src/test/java/org/opensearch/searchrelevance/metrics/calculator/EvaluationTests.java
Labels: skip-changelog, v3.1.0

#76 Fixed names in data file for importing judgments
  src/test/data-esci/esci_us_judgments.json
Labels: skip-changelog

#74 Set limit for number of fields programmatically during index creation
  CHANGELOG.md
  src/main/java/org/opensearch/searchrelevance/common/PluginConstants.java
  src/main/java/org/opensearch/searchrelevance/indices/SearchRelevanceIndicesManager.java
  src/test/data-esci/schema.json
  src/test/java/org/opensearch/searchrelevance/indices/SearchRelevanceIndicesManagerTests.java
  src/test/scripts/demo.sh
  src/test/scripts/demo_hybrid_optimizer.sh
Labels: bug, v3.1.0

#79 Fixed class cast exception when creating hybrid optimizer experiment
  src/main/java/org/opensearch/searchrelevance/metrics/MetricsHelper.java
Labels: skip-changelog

#80 fix script and dependencies
  build.gradle
  src/main/java/org/opensearch/searchrelevance/plugin/SearchRelevancePlugin.java
  src/test/scripts/create_judgments_with_manual_input.sh
  src/test/scripts/demo.sh
Labels: skip-changelog

#87 Update query set schema to avoid too many fields issue
  src/main/java/org/opensearch/searchrelevance/dao/QuerySetDao.java
  src/main/java/org/opensearch/searchrelevance/model/QuerySet.java
  src/main/java/org/opensearch/searchrelevance/model/QuerySetEntry.java
  src/main/java/org/opensearch/searchrelevance/transport/queryset/PostQuerySetTransportAction.java
  src/main/java/org/opensearch/searchrelevance/transport/queryset/PutQuerySetTransportAction.java
  src/main/resources/mappings/queryset.json
  src/test/java/org/opensearch/searchrelevance/indices/SearchRelevanceIndicesManagerTests.java
  src/test/java/org/opensearch/searchrelevance/rest/RestPutQuerySetActionTests.java
Labels: skip-changelog

#88 Bump version on dependencies on jtokkit and diff-coverage-gradle
  build.gradle
  src/main/java/org/opensearch/searchrelevance/ml/TokenizerUtil.java
Labels: skip-changelog

#89 Disable dynamic mapping for object field type
  src/main/java/org/opensearch/searchrelevance/common/PluginConstants.java
  src/main/java/org/opensearch/searchrelevance/indices/SearchRelevanceIndicesManager.java
  src/main/resources/mappings/evaluation_result.json
  src/main/resources/mappings/experiment.json
  src/main/resources/mappings/experiment_variant.json
  src/main/resources/mappings/judgment.json
  src/test/java/org/opensearch/searchrelevance/indices/SearchRelevanceIndicesManagerTests.java
  src/test/scripts/demo.sh
  src/test/scripts/demo_hybrid_optimizer.sh
Labels: skip-changelog

#91 Disabled indexing for some fields in query set and jugments indexes
  src/main/resources/mappings/judgment.json
  src/main/resources/mappings/queryset.json
Labels: skip-changelog

#78 Refresh readme
  README.md
Labels: skip-changelog

#94 Added CI action for publishing to maven repository
  .github/workflows/maven-publish.yml
  build.gradle
  scripts/build.sh
  settings.gradle
Labels: skip-changelog, infrastructure

#100 Fix hybrid search optimizer script
  Dockerfile
  docker-compose.yml
  src/test/scripts/demo_hybrid_optimizer.sh
Labels: skip-changelog

#101 Migrate data schema from object to nested with explicit field
  src/main/java/org/opensearch/searchrelevance/experiment/QuerySourceUtil.java
  src/main/java/org/opensearch/searchrelevance/model/ExperimentVariant.java
  src/main/java/org/opensearch/searchrelevance/model/Judgment.java
  src/main/java/org/opensearch/searchrelevance/transport/experiment/PutExperimentTransportAction.java
  src/main/java/org/opensearch/searchrelevance/transport/judgment/PutJudgmentTransportAction.java
  src/main/resources/mappings/experiment.json
  src/main/resources/mappings/experiment_variant.json
  src/main/resources/mappings/judgment.json
  src/test/java/org/opensearch/searchrelevance/experiment/QuerySourceUtilTests.java
Labels: skip-changelog

#112 Fixed integration tests failures in distribution pipeline
  build.gradle
  src/test/java/org/opensearch/searchrelevance/BaseSearchRelevanceIT.java
Labels: skip-changelog, backport 3.1, failing-tests

#111 bug fix for UBI judgment generation
  src/main/java/org/opensearch/searchrelevance/judgments/UbiJudgmentsProcessor.java
Labels: skip-changelog, backport 3.1

#124 Fixed missing variants in Hybrid Optimizer
  CHANGELOG.md
  src/main/java/org/opensearch/searchrelevance/experiment/ExperimentOptionsForHybridSearch.java
  src/main/java/org/opensearch/searchrelevance/experiment/QuerySourceUtil.java
  src/test/java/org/opensearch/searchrelevance/action/experiments/ExperimentIT.java
  src/test/java/org/opensearch/searchrelevance/experiment/ExperimentOptionsForHybridSearchTests.java
  src/test/java/org/opensearch/searchrelevance/experiment/QuerySourceUtilTests.java
  src/test/resources/data_esci/CreateIndex.json
  src/test/resources/experiment/CreateExperimentHybridOptimizer.json
  src/test/resources/searchconfig/CreateSearchConfigurationHybridQuery.json
Labels: backport 3.1

#133 [Backport 3.1] add validation to input and search configuration length
  README.md
  release-notes/opensearch-search-relevance.release-notes-3.1.0.0.md
  src/main/java/org/opensearch/searchrelevance/common/PluginConstants.java
  src/main/java/org/opensearch/searchrelevance/dao/JudgmentCacheDao.java
  src/main/java/org/opensearch/searchrelevance/metrics/MetricsHelper.java
  src/main/java/org/opensearch/searchrelevance/plugin/SearchRelevancePlugin.java
  src/main/java/org/opensearch/searchrelevance/rest/RestCreateQuerySetAction.java
  src/main/java/org/opensearch/searchrelevance/rest/RestPutExperimentAction.java
  src/main/java/org/opensearch/searchrelevance/rest/RestPutJudgmentAction.java
  src/main/java/org/opensearch/searchrelevance/rest/RestPutQuerySetAction.java
  src/main/java/org/opensearch/searchrelevance/rest/RestPutSearchConfigurationAction.java
  src/main/java/org/opensearch/searchrelevance/settings/SearchRelevanceSettings.java
  src/main/java/org/opensearch/searchrelevance/settings/SearchRelevanceSettingsAccessor.java
  src/main/java/org/opensearch/searchrelevance/utils/TextValidationUtil.java
  src/test/java/org/opensearch/searchrelevance/BaseSearchRelevanceIT.java
  src/test/java/org/opensearch/searchrelevance/plugin/SearchRelevancePluginTests.java
  src/test/java/org/opensearch/searchrelevance/rest/RestCreateQuerySetActionTests.java
  src/test/java/org/opensearch/searchrelevance/rest/RestPutExperimentActionTests.java
  src/test/java/org/opensearch/searchrelevance/rest/RestPutQuerySetActionTests.java
  src/test/java/org/opensearch/searchrelevance/util/TextValidationUtilTest.java
Labels: skip-changelog

#144 Always download demo certs regardless is security.enabled is set to true
  .github/workflows/test_security.yml
  build.gradle
Labels: skip-changelog

#151 Reformatted release notes according to OS stadard schema
  release-notes/opensearch-search-relevance.release-notes-3.1.0.0.md
Labels: skip-changelog, infrastructure

#152 [Upport main] Reformatted release notes according to OS stadard schema (#151)
  CHANGELOG.md
  release-notes/opensearch-search-relevance.release-notes-3.1.0.0.md
Labels: skip-changelog, infrastructure

#135 Changed http client to secured/admin for cases when we work with protected indexes
  src/test/java/org/opensearch/searchrelevance/action/experiments/ExperimentIT.java
Labels: skip-changelog
