Repository opensearch-project/search-relevance, pull requests merged in 2025-07, with the labels that each got.

#166 introduce task scheduler to create LLM judgment as batches
  CHANGELOG.md
  src/main/java/org/opensearch/searchrelevance/dao/JudgmentCacheDao.java
  src/main/java/org/opensearch/searchrelevance/executors/JudgmentResponseProcessor.java
  src/main/java/org/opensearch/searchrelevance/executors/JudgmentTaskContext.java
  src/main/java/org/opensearch/searchrelevance/executors/LlmJudgmentTaskManager.java
  src/main/java/org/opensearch/searchrelevance/indices/SearchRelevanceIndicesManager.java
  src/main/java/org/opensearch/searchrelevance/judgments/JudgmentDataTransformer.java
  src/main/java/org/opensearch/searchrelevance/judgments/JudgmentsProcessorFactory.java
  src/main/java/org/opensearch/searchrelevance/judgments/LlmJudgmentsProcessor.java
  src/main/java/org/opensearch/searchrelevance/ml/ChunkProcessingContext.java
  src/main/java/org/opensearch/searchrelevance/ml/ChunkResult.java
  src/main/java/org/opensearch/searchrelevance/ml/MLAccessor.java
  src/main/java/org/opensearch/searchrelevance/ml/MLInputOutputTransformer.java
  src/main/java/org/opensearch/searchrelevance/model/JudgmentBatchStatus.java
  src/test/java/org/opensearch/searchrelevance/executors/JudgmentDataTransformerTests.java
  src/test/java/org/opensearch/searchrelevance/executors/JudgmentResponseProcessorTests.java
  src/test/java/org/opensearch/searchrelevance/executors/JudgmentTaskContextTests.java
  src/test/java/org/opensearch/searchrelevance/ml/ChunkProcessingContextTests.java
Labels: enhancement, v3.2.0

#176 bug fix on rest APIs error status for creations
  CHANGELOG.md
  src/main/java/org/opensearch/searchrelevance/exception/SearchRelevanceException.java
  src/main/java/org/opensearch/searchrelevance/rest/RestCreateQuerySetAction.java
  src/main/java/org/opensearch/searchrelevance/rest/RestPutExperimentAction.java
  src/main/java/org/opensearch/searchrelevance/rest/RestPutJudgmentAction.java
  src/main/java/org/opensearch/searchrelevance/rest/RestPutQuerySetAction.java
  src/main/java/org/opensearch/searchrelevance/rest/RestPutSearchConfigurationAction.java
  src/test/java/org/opensearch/searchrelevance/rest/RestDeleteQuerySetActionTests.java
  src/test/java/org/opensearch/searchrelevance/rest/RestDeleteSearchConfigurationActionTests.java
  src/test/java/org/opensearch/searchrelevance/rest/RestPutJudgmentActionTests.java
Labels: bug, v3.1.0

#185 Replace autocut to dependabot to skip changelog update check
  .github/workflows/changelog.yml
Labels: skip-changelog

#192 Revert dashboard fields changes of PR#190 to MetricsHelper.
  src/main/java/org/opensearch/searchrelevance/metrics/MetricsHelper.java
  src/main/java/org/opensearch/searchrelevance/model/EvaluationResult.java
Labels: skip-changelog

#188 Upgrade gradle to 8.14 and JDK 23->24
  .github/workflows/CI.yml
  .github/workflows/test_security.yml
  CHANGELOG.md
  DEVELOPER_GUIDE.md
  gradle/wrapper/gradle-wrapper.properties
Labels: infrastructure

#195 Flipping defaulted srw enable flag to true
  src/main/java/org/opensearch/searchrelevance/settings/SearchRelevanceSettings.java
  src/test/java/org/opensearch/searchrelevance/plugin/SearchRelevancePluginTests.java
Labels: skip-changelog

#198 bug fix for experiment stuck at "PROCESSING" status
  src/main/java/org/opensearch/searchrelevance/transport/experiment/PutExperimentTransportAction.java
  src/test/java/org/opensearch/searchrelevance/transport/experiment/PutExperimentTransportActionTests.java
Labels: skip-changelog

#199 UBI plugin is now part of OpenSearch, so simplify demo script by removing the --skip-ubi feature
  src/test/scripts/demo.sh
Labels: skip-changelog
