Repository opensearch-project/search-relevance, pull requests merged in 2025-05, with the labels that each got.

#3 Creating initial file from plugin-template
  .gitattributes
  .github/dependabot.yml
  .github/workflows/CI.yml
  .github/workflows/backport.yml
  .gitignore
  .whitesource
  DEVELOPER_GUIDE.md
  README.md
  build.gradle
  formatter/formatterConfig.xml
  formatter/formatting.gradle
  formatter/license-header.txt
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/org/opensearch/searchrelevance/common/Constants.java
  src/main/java/org/opensearch/searchrelevance/plugin/SearchRelevancePlugin.java
  src/main/java/org/opensearch/searchrelevance/rest/RestCreateQuerySetAction.java
  src/main/java/org/opensearch/searchrelevance/transport/QuerySetAction.java
  src/main/java/org/opensearch/searchrelevance/transport/QuerySetRequest.java
  src/main/java/org/opensearch/searchrelevance/transport/QuerySetResponse.java
  src/main/java/org/opensearch/searchrelevance/transport/QuerySetTransportAction.java
  src/test/java/org/opensearch/searchrelevance/action/QuerySetActionTests.java
  src/test/java/org/opensearch/searchrelevance/plugin/SearchRelevancePluginIT.java
  src/test/java/org/opensearch/searchrelevance/plugin/SearchRelevanceTests.java
  src/test/java/org/opensearch/searchrelevance/rest/RestQuerySetActionIT.java
  src/yamlRestTest/java/org/opensearch/searchrelevance/plugin/SearchRelevanceClientYamlTestSuiteIT.java
  src/yamlRestTest/resources/rest-api-spec/test/10_basic.yml
Labels: skip-changelog

#13 Updated project README and debug configuration
  .idea/copyright/SPDX_ALv2.xml
  .idea/copyright/profiles_settings.xml
  .idea/runConfigurations/DebugSearchRelevance.xml
  .idea/runConfigurations/RunSearchRelevance.xml
  .idea/runConfigurations/RunWithDebugPort.xml
  DEVELOPER_GUIDE.md
  README.md
  SECURITY.md
Labels: skip-changelog, infrastructure

#24 Added support for Lombok annotations
  build.gradle
  src/main/java/org/opensearch/searchrelevance/model/ubi/event/EventObject.java
  src/main/java/org/opensearch/searchrelevance/rest/RestPutExperimentAction.java
Labels: skip-changelog, infrastructure

#27 LLM Judgment Processor Improvements
  CHANGELOG.md
  src/main/java/org/opensearch/searchrelevance/common/PluginConstants.java
  src/main/java/org/opensearch/searchrelevance/dao/JudgmentCacheDao.java
  src/main/java/org/opensearch/searchrelevance/dao/SearchConfigurationDao.java
  src/main/java/org/opensearch/searchrelevance/judgments/LlmJudgmentsProcessor.java
  src/main/java/org/opensearch/searchrelevance/ml/ChunkException.java
  src/main/java/org/opensearch/searchrelevance/ml/ChunkResult.java
  src/main/java/org/opensearch/searchrelevance/ml/MLAccessor.java
  src/main/java/org/opensearch/searchrelevance/model/ExperimentType.java
  src/main/java/org/opensearch/searchrelevance/plugin/SearchRelevancePlugin.java
  src/main/java/org/opensearch/searchrelevance/rest/RestPutExperimentAction.java
  src/main/java/org/opensearch/searchrelevance/rest/RestPutJudgmentAction.java
  src/main/java/org/opensearch/searchrelevance/transport/experiment/PutExperimentTransportAction.java
  src/main/java/org/opensearch/searchrelevance/transport/experiment/PutLlmExperimentRequest.java
  src/main/java/org/opensearch/searchrelevance/transport/judgment/PutJudgmentTransportAction.java
  src/main/java/org/opensearch/searchrelevance/transport/judgment/PutLlmJudgmentRequest.java
  src/main/java/org/opensearch/searchrelevance/utils/ParserUtils.java
  src/test/java/org/opensearch/searchrelevance/plugin/SearchRelevancePluginTests.java
Labels: enhancement
